### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by hamin** [jgpavez/MedicalDiagnosis#1]
Hi there. Came across your project and looks really cool :) . I was wondering if the dataset that you used to create the model can be included in the repo? If not, is it a public dataset that can be accessed from somewhere else? Thanks again :)

**Comment by jgpavez** [comment]
Hi Haris, Thanks!, I'm glad you like the project. Sadly I can't include the
dataset right now. However the data mainly consist of descriptions of
diseases that you can find in wikipedia or webmd. Also, you can check the
MIMIC dataset https://mimic.physionet.org/.

2017-01-25 13:48 GMT-03:00 Haris Amin <notifications@github.com>:

**Comment by hamin** [comment]
@jgpavez awesome! Thank you very much!
